ch99/blog/urls.py
from django.urls import path,re_path
from blog import views

app_name = 'blog'
urlpatterns = [
        #Example: /blog/
        path('',views.PostLV.as_view(),name= 'index'),

        #Example: /blog/post/
        path('post/',views.PostLV.as_view(),name='post_list'),

        #Example: /blog/post/[특이한 내용]
        re_path(r'^post/(?P<slug>[-\w]+)/$',views.PostDV.as_view(),name='post_detail'),

        #Example: /blog/archive/
        path('archive/',views.PostAV.as_view(),name='post_archive'),

        #Example: /blog/archive/2020
        path('archive/<int:year>/',views.PostYAV.as_view(),name='post_year_archive'),
        #Example: /blog/archive/2020/Dec
        path('archive/<int:year>/<str:month>/',views.PostMAV.as_view(),name='post_month_archive'),
        #Example: /blog/archive/2020
        path('archive/<int:year>/<str:month>/<int:day>/',views.PostDAV.as_view(),name='post_day_archive'),
        #Example: /blog/archive/today/
        path('archive/today/',views.PostTAV.as_view(),name='post_today_archive'),
        #Example: /blog/tag/
        path('tag/',views.TagCloudTV.as_view(), name='tag_cloud'),

        path('tag/<str:tag>/',views.TaggedObjectLV.as_view(),name = 'tagged_object_list'),
        #Example: /blog/search/
        path('search/',views.SearchFormView.as_view(),name = 'search'),

        # Example: /blog/add/
        path('add/',views.PostCreateView.as_view(), name="add",),

        # Example: /blog/change/
        path('change/',views.PostChangeLV.as_view(), name="change",),

        # Example: /blog/99/update/
        path('<int:pk>/update/',views.PostUpdateView.as_view(), name="update",),

        # Example: /blog/99/delete/
        path('<int:pk>/delete/',views.PostDeleteView.as_view(), name="delete",),

]

ch99/bookmark/urls.py
from django.urls import path
#from bookmark.views import BookmarkLV, BookmarkDV
from bookmark import views

app_name = 'bookmark'
urlpatterns = [
        path('',views.BookmarkLV.as_view(),name='index'),
        path('<int:pk>/',views.BookmarkDV.as_view(),name='detail'),
        #/bookmark/add/
        path('add/',views.BookmarkCreateView.as_view(),name="add",),
        #/bookmark/change/
        path('change/',views.BookmarkChangeLV.as_view(),name="change",),
        #/bookmark/99/update/
        path('<int:pk>/update/', views.BookmarkUpdateView.as_view(),name="update",),

        #/bookmark/99/delete/
        path('<int:pk>/delete/',views.BookmarkDeleteView.as_view(),name="delete",),
]

ch99/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
#from django.conf.urls.static import static
#from django.conf import settings
from mysite.views import UserCreateView, UserCreateDoneTV

from mysite.views import HomeView
#다음은 APP_URLCONF로 이동
#from bookmark.views import BookmarkLV, BookmarkDV #뷰 모듈과 관련된 클래스를 임포트
#from bookmark.view import * 와 같이 일괄처리도 가능

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/register/',UserCreateView.as_view(), name='register'),
    path('accounts/register/done/',UserCreateDoneTV.as_view(),name='register_done'),
    
    path('',HomeView.as_view(),name='home'),
    path('bookmark/',include('bookmark.urls')),
    path('blog/',include('blog.urls')),
    path('photo/',include('photo.urls'))
    #move to APP_URLCONF
    #class-based views
    #path('bookmark/',BookmarkLV.as_view(),name='index'),
    #path('bookmark/<int:pk>/',BookmarkDV.as_view(),name='detail'),
]#+ static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

ch99/photo/urls.py
from django.urls import path

from photo import views


app_name = 'photo'
urlpatterns = [

    # Example: /photo/
    path('', views.AlbumLV.as_view(), name='index'),

    # Example: /photo/album/, same as /photo/
    path('album', views.AlbumLV.as_view(), name='album_list'),

    # Example: /photo/album/99/
    path('album/<int:pk>/', views.AlbumDV.as_view(), name='album_detail'),

    # Example: /photo/photo/99/
    path('photo/<int:pk>/', views.PhotoDV.as_view(), name='photo_detail'),

    # Example: /photo/album/add/
    path('album/add/', views.AlbumPhotoCV.as_view(), name='album_add'),

    # Example: /photo/album/change/
    path('album/change/', views.AlbumChangeLV.as_view(), name='album_change'),

    # Example: /photo/album/99/update/
    path('album/<int:pk>/update/', views.AlbumPhotoUV.as_view(), name='album_update'),

    # Example: /photo/album/99/delete/
    path('album/<int:pk>/delete/', views.AlbumDelV.as_view(), name='album_delete'),

    # Example: /photo/photo/add/
    path('photo/add/', views.PhotoCV.as_view(), name='photo_add'),

    # Example: /photo/photo/change/
    path('photo/change/', views.PhotoChangeLV.as_view(), name='photo_change'),

    # Example: /photo/photo/99/update/
    path('photo/<int:pk>/update/', views.PhotoUV.as_view(), name='photo_update'),

    # Example: /photo/photo/99/delete/
    path('photo/<int:pk>/delete/', views.PhotoDelV.as_view(), name='photo_delete'),

]

ch99/templates/base.html
<!DOCTYPE html>
<html lang = "ko">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="chrome=1">
        <meta name ="viewport" content="width=device-width, initial-scale=1">

        <title>{% block title %}4rtist{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet">

        {% block extra-style %}{% endblock %}
    </head>
    <body style = "padding-top:90px;">
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
            <div class="container-fluid">
              <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">4rtist</span>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'bookmark:index' %}">SNS</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      ART
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li><a class="dropdown-item" href="{% url 'blog:index' %}">MUSIC</a></li>
                      <li><a class="dropdown-item" href="{% url 'blog:post_archive'%}">VIDEO ART</a></li>
                      <li><a class="dropdown-item" href="{% url 'blog:search' %}">DRAWING</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{% url 'photo:index' %}">DANCE</a></li>
                    </ul>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Admin</a>
                  </li>
                </ul>
                <form class="d-flex">
                  <input class="form-control me-2" type="search" placeholder="global search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>

                <ul class="navbar-nav ml-5 mr-5">
                  <li class="nav-item dropdown mx-1 btn btn-primary">
                    <a class="nav-link dropdown-toggle text-white" href="#" id = "navbarDropdown" role = "button" data-bs-toggle="dropdown" aria-expanded="false">Add</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'bookmark:add' %}">Bookmark</a>
                        <a class="dropdown-item" href="{% url 'blog:add' %}">Post</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'photo:album_add' %}">Album</a>
                        <a class="dropdown-item" href="{% url 'photo:photo_add' %}">Photo</a>
                    </div>
                  </li>
                  <li class="nav-item dropdown mx-1 btn btn-primary">
                    <a class="nav-link dropdown-toggle text-white" href="#" id = "navbarDropdown" role = "button" data-bs-toggle="dropdown" aria-expanded="false">Change</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'bookmark:change' %}">Bookmark</a>
                        <a class="dropdown-item" href="{% url 'blog:change' %}">Post</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'photo:album_add' %}">Album</a>
                        <a class="dropdown-item" href="{% url 'photo:photo_add' %}">Photo</a>
                    </div>
                  </li>
                  <li class="nav-item dropdown mx-1 btn btn-primary">
                      {% if user.is_active %}
                      <a class="nav-link dropdown-toggle text-white" href="#" id = "navbarDropdown" role = "button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;</a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                        <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                      </div>
                      {% else %}
                      <a class="nav-link dropdown-toggle text-white" href="#" id = "navbarDropdown" role = "button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-user"></i>&ensp;Anonymous&ensp;</a>
                      <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                        <a class="dropdown-item" href="{% url 'register' %}">Register</a>
                      </div>
                      {% endif %}
                  </li>
                </ul>
              </div>
            </div>
          </nav>
        <div class="container bg-warning">
            {% block content %}{% endblock %}
        </div>

        {% block footer %}{% endblock %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js">
        </script>
        {% block extra-script %}
        {% endblock %}
    </body>

</html>

ch99/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}home.html{% endblock %}

{% block extra-style %}
<style type="text/css">
.home-image{
    background-image: url("{% static 'img/main_page.jpeg' %}");
    background-repeat: no-repeat;
    background-position: center;
    background-size: 100%;
    height:500px;
    border: 1-px solid rgb(204, 204, 204);
    border-bottom: 10px solid yellow;
    padding: 20px 0 0 20px;
}
.title{
    color: #000;
    font-weight: bold;
}
.powered{
    position: relative;
    top: 77%;
    color: #0000ff;
    font-style: italic;
}
</style>
{% endblock %}

{% block content %}
    <div class="home-image">
        <h2 class="title">4rtist</h2>
        <h4 class="powered"><i class="fas fa-arrow-circle-right"></i>for Artist.</h4>
    </div>
    <hr style="margin: 10px 0;">

    <div class = "row text-center">
        <div class = "col-sm-6">
            <h3>Artist</h3>
            <p>We can connect every Artist! Come on and find your Artist!!</p>
        </div>
        <div class = "col-sm-6">
            <h3>Art</h3>
            <p>We can share every Art made by Our Artist! Come on and enjoy Art!</p>
        </div>
    </div>
{% endblock content %}

{% block footer %}
<footer class="fixed-bottom bg-info">
    <div class = "text-white font-italic text-right mr-5">Copyright &copy;2021 System by SW Engieneer Hong</div>
</footer>
{% endblock %}